/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface RxdbTest {
        "userId": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLRxdbTestElement extends Components.RxdbTest, HTMLStencilElement {
    }
    var HTMLRxdbTestElement: {
        prototype: HTMLRxdbTestElement;
        new (): HTMLRxdbTestElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "rxdb-test": HTMLRxdbTestElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface RxdbTest {
        "userId"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "rxdb-test": RxdbTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "rxdb-test": LocalJSX.RxdbTest & JSXBase.HTMLAttributes<HTMLRxdbTestElement>;
        }
    }
}
